---
title: "Data Exercise (option 2)"
---
```{r}
set.seed(123) #random number generator
```

## Generate synthetic data
```{r}
n <- 1200 
#setting n equal to 1200
```

# Demographics / baseline predictors
```{r}
age <- round(rnorm(n, mean = 35, sd = 12)) #creates age as a variable
age <- pmax(pmin(age, 70), 18)  #limits the age range between 18 and 70                
sex <- factor(rbinom(n, 1, 0.55), labels = c("F", "M"))

study_hours <- pmax(rnorm(n, mean = 12, sd = 5), 0) #generates random study times
exercise_hours <- pmax(4 - 0.12 * study_hours + rnorm(n, 0, 1.8), 0)
tutoring <- rbinom(n, 1, plogis(-1 + 0.10 * study_hours))
ability <- rnorm(n, 0, 1)
```

# Outcomes
```{r}
score <- 55 +
  2.4 * study_hours +
  1.2 * exercise_hours +
  3.0 * (sex == "M") +
  6.5 * ability +
  0.08 * age - 0.0015 * age^2 +                 
  rnorm(n, 0, 10)

# Binary outcome based on a logistic model:
p_pass <- plogis(-10 + 0.14 * score + 0.35 * tutoring)
passed <- rbinom(n, 1, p_pass)
```

```{r}

# outcome to illustrate a different model (stress, coffee, exercise, ability, study):
stress <- 0.6 * scale(study_hours)[,1] - 0.7 * scale(exercise_hours)[,1] - 0.4 * ability + rnorm(n, 0, 0.6)
lambda_coffee <- exp(1.2 + 0.35 * stress)
coffee <- rpois(n, lambda_coffee)

# data frame
dat <- data.frame(
  age, sex, study_hours, exercise_hours,
  tutoring = factor(tutoring, labels = c("no", "yes")),
  ability, score, passed = factor(passed, labels = c("no", "yes")),
  stress, coffee
)
```

## Data
```{r}
# Summary
summary(dat)

# Creates a dataset called nums_vars
num_vars <- dat[, c("age","study_hours","exercise_hours","ability","score","stress","coffee")]
round(cor(num_vars), 2)

# Tables for categorical vars
table(dat$sex)
table(dat$tutoring)
prop.table(table(dat$passed))
op <- par(mfrow = c(2, 2), mar = c(4,4,2,1))

# Score vs study
plot(dat$study_hours, dat$score,
     xlab = "Study hours", ylab = "Score", main = "Score vs Study hours")
abline(lm(score ~ study_hours, dat), lwd = 2)

# Exercise vs study 
plot(dat$study_hours, dat$exercise_hours,
     xlab = "Study hours", ylab = "Exercise hours", main = "Exercise vs Study")
abline(lm(exercise_hours ~ study_hours, dat), lwd = 2)

# Score by tutoring
barplot(prop.table(table(dat$passed, dat$tutoring), 2)["yes", ],
        ylab = "P(passed = yes)", main = "Pass rate by tutoring", ylim = c(0,1))

# Coffee vs stress
plot(dat$stress, dat$coffee,
     xlab = "Stress", ylab = "Coffee (count)", main = "Coffee vs Stress")
```

## Fit models

```{r}

# Linear models
m1 <- lm(score ~ study_hours + exercise_hours + sex + age, data = dat)
summary(m1)

m2 <- lm(score ~ study_hours + exercise_hours + sex + age + I(age^2), data = dat)
summary(m2)

m3 <- lm(score ~ study_hours + exercise_hours + sex + age + I(age^2) + ability, data = dat)
summary(m3)

# Comparing all the variables
AIC(m1, m2, m3)
```